name: ai_query_assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - black>=23.7.0
  - pylint>=2.17.5
  - tomli>=2.0.1
  - postgresql>=15.0
  - pip:
      - langchain>=0.1.0
      - langchain-core>=0.1.0
      - langchain-community>=0.0.10
      - langchain-openai>=0.0.1
      - langchain-experimental>=0.0.49
      - langchain-ollama>=0.0.1
      - langgraph>=0.0.20
      - python-dotenv>=1.0.0
      - isort>=5.12.0
      - sqlalchemy>=2.0.0
      - psycopg2-binary>=2.9.9
      - alembic>=1.13.0
      - pydantic>=2.0.0
      - httpx>=0.24.0
      - anyio>=4.0.0 
      - openlit>=1.33.8