apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: ${POSTGRES_USER:-postgres}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-postgres}
    jsonData:
      database: ${POSTGRES_DB:-testdb}
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    editable: true